In [1]:
import tensorflow as tf
import numpy as np
import math

In [2]:
sess = tf.InteractiveSession()

In [3]:
# Some simple constants
x1 = tf.Variable(tf.truncated_normal([5],
                 mean=3, stddev=1./math.sqrt(5)))
x2 = tf.Variable(tf.truncated_normal([5],
                 mean=-1, stddev=1./math.sqrt(5)))
x3 = tf.Variable(tf.truncated_normal([5],
                 mean=0, stddev=1./math.sqrt(5)))

sess.run(tf.global_variables_initializer())

In [4]:
# Squaring makes large values extreme (but positive)
# Be careful if you have negative values
sqx2 = x2 * x2
print(x2.eval())
print(sqx2.eval())

[-1.3843977 -1.1147864 -1.646596  -0.5979958 -0.5030011]
[1.9165571 1.2427487 2.7112782 0.357599  0.2530101]


In [5]:
# Logarithm makes small values more pronounced (and negative)
# Be careful that your algorithm can handle negative numbers
logx1 = tf.log(x1)
print(x1.eval())
print(logx1.eval())

[2.2528636 3.866387  2.8785934 2.7533782 2.9464304]
[0.81220216 1.3523204  1.0573018  1.0128286  1.0805944 ]


In [6]:
# "sigmoid" is a common transformation in deep learning
# Extreme values get flattened to +1 or 0
# Inputs closer to zero stay similar, sigmoid(0) = 0.5
sigx3 = tf.sigmoid(x3)
print(x3.eval())
print(sigx3.eval())

[ 0.13119844 -0.05276553 -0.57573414  0.5720304   0.50682586]
[0.53275263 0.48681167 0.35991475 0.63923156 0.6240621 ]


In [7]:
# We linearly combine multiple inputs, then transform
w1 = tf.constant(0.1)
w2 = tf.constant(0.2)
sess.run(tf.global_variables_initializer())
n1 = tf.sigmoid(w1*x1 + w2*x2)
print((w1*x1).eval())
print((w2*x2).eval())
print(n1.eval())

[0.31981993 0.31209084 0.2212714  0.31921357 0.23425284]
[-0.26690024 -0.23812762 -0.03211142 -0.20859893 -0.17633913]
[0.51322687 0.5184824  0.5471495  0.5276255  0.5144744 ]


In [ ]:
#Single hidden layer model 